#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use BananaPHP\Foundation\Application;
use App\Console\Kernel;

$app = new Application(dirname(__DIR__));

$kernel = $app->make(Kernel::class);
$status = $kernel->handle(
    new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

exit($status);